### ISSUE TITLE
偶尔报错

### ISSUE THREAD

**Issue by CNYuYang** [fastgh/fgit#1]
[fgit] 程序崩溃, 错误原因: 登录失败: Get "https://control.fastgithub.com:10443/api/v1/account/_/beb3314c-2fed-11eb-a4a8-0242ac140002/LoginByID?password=b8916d48-2fed-11eb-b835-acde48001122": dial tcp: lookup control.fastgithub.com on 180.76.76.76:53: read udp 192.168.31.173:57091->180.76.76.76:53: i/o timeout

<img width="711" alt="QQ20201128-181407@2x" src="https://user-images.githubusercontent.com/42082796/100499571-9428d180-31a5-11eb-993b-241a14fea085.png">

**Comment by qiangyt** [comment]
这个暂时没找到解决办法，是服务器端线路问题

**Comment by qiangyt** [comment]
如果频繁出现，请留个言，考虑搬服务器

**Comment by CNYuYang** [comment]
新错误
<img width="1018" alt="QQ20201205-145627@2x" src="https://user-images.githubusercontent.com/42082796/101236197-22eba000-370a-11eb-977e-254bbc12dee5.png">

**Comment by qiangyt** [comment]
你改了系统时间吗？你的系统时间是2020-11-15T06:57:57，而服务器的证书是2020-11-20T17:38申请的，11-15时还没开始生效，你得自己改回来

**Comment by CNYuYang** [comment]
> 你改了系统时间吗？你的系统时间是2020-11-15T06:57:57，而服务器的证书是2020-11-20T17:38申请的，11-15时还没开始生效，你得自己改回来

哦哦，知道了。在虚拟机里面用的，没有设置时区。
