### ISSUE TITLE
[fgit] 程序崩溃, 错误原因: 登录失败

### ISSUE THREAD

**Issue by 5idu** [fastgh/fgit#3]
### 错误信息
[fgit] 程序崩溃, 错误原因: 登录失败: Get "https://control.fastgithub.com:10443/api/v1/account/_/10e47730-3b75-11eb-a088-0242anByID?password=xxx": dial tcp: i/o timeout

**Comment by 5idu** [comment]
it' ok now!

**Comment by chaotianjiao** [comment]
![image](https://user-images.githubusercontent.com/42534375/114136591-89ddc780-993d-11eb-9df0-9a28bc11a668.png)
这个有办法解决吗大佬？
