### ISSUE TITLE
可不可以配置文件设置账户密码？

### ISSUE THREAD

**Issue by HickeyHsu** [fastgh/fgit#4]
每次push/pull都要输入账户密码好麻烦。。不知道有没有配置文件可以直接配置账户密码？

**Comment by zhupengfeivip** [comment]
> 每次push/pull都要输入账户密码好麻烦。。不知道有没有配置文件可以直接配置账户密码？

这和fgit没有关系吧，是你git没有配置用户名和密码吧，所以每次都要输入。
试试
git config --global user.name "xxx"
git config --global user.email "xxx@xxx.com"

**Comment by qiangyt** [comment]
可以这样：git pull https://用户名:密码@github.com/.......
