### ISSUE TITLE
程序崩溃, 错误原因: 账号注册失败: 

### ISSUE THREAD

**Issue by test-black** [fastgh/fgit#5]
Post "https://control.fastgithub.com:10443/api/v1/account?password=9548547d-7487-11ec-903a-525400a380a3": dial tcp 80.251.214.199:10443: connect: connection refused

**Comment by traddo** [comment]
osx， 同样也是这个问题

**Comment by simplew2011** [comment]
[fgit] 程序崩溃, 错误原因: 账号注册失败: Post "https://control.fgit.kailash.cloud:10443/api/v1/account?password=98699641-215e-11ee-8cbd-7486e2xxxxxx7": dial tcp: lookup control.fgit.kailash.cloud: no such host

**Comment by RWDai** [comment]
一样 不可用

**Comment by qiangyt** [comment]
因为服务器停了，需要修改下，去掉服务器连接功能，稍后会发布一个版本

**Comment by qiangyt** [comment]
刚试过，可用

**Comment by duxin0618** [comment]
[fgit] 程序崩溃, 错误原因: JSON反序列化失败: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

: invalid character '<' looking for beginning of value
堆栈:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
main.main.func1()
	/data/qiangyt/gogs/fgit/fgit/main.go:62 +0x44
panic({0x105158620, 0x14000284090})
	/usr/local/go/src/runtime/panic.go:884 +0x204
main.JSONUnmarshal({0x140002ac000, 0xa6}, {0x10512ec00, 0x140002a8010})
	/data/qiangyt/gogs/fgit/fgit/util.go:106 +0xb4
main.CreateAccount({0x1050a4935?, 0x14?}, {0x1400013e240, 0x24})
	/data/qiangyt/gogs/fgit/fgit/api_client.go:150 +0x1c8
main.LoadConfig()
	/data/qiangyt/gogs/fgit/fgit/config.go:52 +0x54
main.main()
	/data/qiangyt/gogs/fgit/fgit/main.go:93 +0x298
