### ISSUE TITLE
No support for -- recursive😂

### ISSUE THREAD

**Issue by gtr3qq** [fastgh/fgit#9]
😂cao CN-Mobile, mofo keeps injecting EOF to the connection, if it connects at all.

Thank you soo much for this EZ tool, but it's a bit oof if --recursive's not supported........

e.g. [github/ ](https://github.com/tildearrow/furnace) requires all the extrn libs there to compile.

**Comment by qiangyt** [comment]
抱歉，目前没精力做大的改动，所以没计划支持。

**Comment by gtr3qq** [comment]
rips😂.

Well, thanks a lot.
